version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static:ro  # ← Agregar este volumen
    restart: unless-stopped
    networks:
      - custom_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro  # ← Mismo volumen para Nginx
    restart: unless-stopped
    networks:
      - custom_network

networks:
  custom_network:
    name: custom_network # Nombre explícito para la red
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.12.0/28
          gateway: 172.42.12.1